// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFabCwj5lQ6S6zEA72CTk7tKxGqnbMS-s',
    appId: '1:990054450218:android:fcbe209f0cab8bfbbb2f53',
    messagingSenderId: '990054450218',
    projectId: 'pitbowl-app',
    databaseURL: 'https://pitbowl-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pitbowl-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVovRIZC0cVJ58ZkTdKUmBiFKTT5u7kCo',
    appId: '1:990054450218:ios:3c5406e29942dbc7bb2f53',
    messagingSenderId: '990054450218',
    projectId: 'pitbowl-app',
    databaseURL: 'https://pitbowl-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pitbowl-app.appspot.com',
    iosClientId: '990054450218-l2gknbp3mpfbojjh3n0ebhtpv9di3v90.apps.googleusercontent.com',
    iosBundleId: 'com.example.pitbowl',
  );

}